"""Collect every results/*/metrics.json (and run_meta.json) into results/SUMMARY.md and results/summary.csv."""

import csv
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
RESULTS = HERE / "results"

ORDER = ["synthetic_pool", "synthetic_pool_caustics", "tum_freiburg1_xyz", "tum_freiburg3_long_office_household",
         "aqualoc_harbor_07", "pool_raw", "pool_width_scaled"]


def fmt(x, spec):
    return "n/a" if x is None else format(x, spec)


def main():
    rows = []
    for run in sorted(RESULTS.iterdir()):
        if not (run / "run_meta.json").exists():
            continue
        meta = json.loads((run / "run_meta.json").read_text())
        m = json.loads((run / "metrics.json").read_text()) if (run / "metrics.json").exists() else {}
        method = meta.get("method", "monoslam")
        label = f"ours ({meta.get('frontend', '?').upper()})" if method == "monoslam" else f"COLMAP ({method.split('_', 1)[1]})"
        if meta.get("stride", 1) > 1:
            label += f", 1 frame in {meta['stride']}"
        rows.append(dict(
            dataset=meta["dataset"], method=label, run=run.name,
            frames=meta["frames_total"], posed=meta.get("frames_posed"),
            posed_pct=100.0 * meta.get("fraction_posed", 0.0),
            status=m.get("status", "no ground truth"),
            ate_rmse_m=m.get("ate_m", {}).get("rmse"), ate_median_m=m.get("ate_m", {}).get("median"),
            ate_max_m=m.get("ate_m", {}).get("max"), ate_pct=m.get("ate_rmse_percent_of_path"),
            path_m=m.get("gt_path_length_m"), scale=m.get("sim3_scale"),
            rpe_t_m=(m.get("rpe_translation_m") or {}).get("rmse"), rpe_r_deg=(m.get("rpe_rotation_deg") or {}).get("rmse"),
            orient_deg=(m.get("orientation_error_deg") or {}).get("rmse"),
            map_surface_median_m=(m.get("map_to_surface_m") or {}).get("median"),
            maps=len(meta.get("maps") or []) or (len(meta["models"]) if meta.get("models") else 1),
            posed_all_maps=meta.get("frames_posed_any_map", meta.get("frames_posed")),
            ate_all_maps_m=(m.get("all_maps") or {}).get("ate_rmse_m_each_map_aligned_separately"),
            keyframes=meta.get("keyframes"), points=meta.get("map_points"),
            runtime_s=meta.get("runtime_seconds")))
    rows.sort(key=lambda r: (ORDER.index(r["dataset"]) if r["dataset"] in ORDER else 99, r["method"]))
    with open(RESULTS / "summary.csv", "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    lines = ["# Results summary", "",
             "Generated by `summarize.py` from `results/*/metrics.json`. ATE is after Sim(3) alignment on the posed",
             "frames only; read it together with the posed fraction. PARTIAL means under 95 % of frames were posed.",
             "RPE is per 1 m of ground truth travel. Map error is only available for the synthetic scenes.",
             "'maps' counts the maps a run built after losing track (COLMAP: models); 'posed, all maps' and",
             "'ATE, all maps' use every map, each aligned by its own Sim(3). Columns without that note use the primary map only.", "",
             "| dataset | method | posed (primary map) | status | ATE RMSE [m] | ATE % path | path [m] | RPE t [m/1 m] | RPE r [deg/1 m] | map median err [m] | maps | posed, all maps | ATE, all maps [m] | runtime [s] |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['dataset']} | {r['method']} | {r['posed']}/{r['frames']} ({r['posed_pct']:.0f} %) | {r['status']} | "
                     f"{fmt(r['ate_rmse_m'], '.4f')} | {fmt(r['ate_pct'], '.2f')} | {fmt(r['path_m'], '.2f')} | "
                     f"{fmt(r['rpe_t_m'], '.4f')} | {fmt(r['rpe_r_deg'], '.2f')} | {fmt(r['map_surface_median_m'], '.4f')} | "
                     f"{r['maps']} | {r['posed_all_maps']} | {fmt(r['ate_all_maps_m'], '.4f')} | "
                     f"{fmt(r['runtime_s'], '.0f')} |")
    (RESULTS / "SUMMARY.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
